org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

java_version=21
mod_loader=Fabric

mod_group=com.example.examplemod
mod_version=1.0.0

mod_id=examplemod
mod_name=Example Mod
mod_filename=ExampleMod

#mc_username=
#mc_uuid=

#release_type=release
#release_loaders=Fabric
#release_minecraft_versions=1.21.4

#curseforge_id=
#curseforge_environments=Server,Client
#curseforge_java_versions=21

#modrinth_id=