[versions]
neogradle = "7.0.170"
minecraft = "1.21.1"
neoforge = "21.1.176"

[libraries]
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }

[plugins]
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
